package jp.co.create.dto;

import java.io.Serializable;

/**
 * 投稿記事 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Article implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 投稿ID. */
	private Integer articleId;

	/** 投稿タイトル. */
	private String articleName;

	/** 投稿値段. */
	private Integer articlePost;

	/** ユーザID. */
	private Integer userId;

	/**
	 * コンストラクタ.
	 */
	public Article() {
	}

	/**
	 * 投稿ID を設定します.
	 * 
	 * @param articleId
	 *            投稿ID
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	/**
	 * 投稿ID を取得します.
	 * 
	 * @return 投稿ID
	 */
	public Integer getArticleId() {
		return this.articleId;
	}

	/**
	 * 投稿タイトル を設定します.
	 * 
	 * @param articleName
	 *            投稿タイトル
	 */
	public void setArticleName(String articleName) {
		this.articleName = articleName;
	}

	/**
	 * 投稿タイトル を取得します.
	 * 
	 * @return 投稿タイトル
	 */
	public String getArticleName() {
		return this.articleName;
	}

	/**
	 * 投稿値段 を設定します.
	 * 
	 * @param articlePost
	 *            投稿値段
	 */
	public void setArticlePost(Integer articlePost) {
		this.articlePost = articlePost;
	}

	/**
	 * 投稿値段 を取得します.
	 * 
	 * @return 投稿値段
	 */
	public Integer getArticlePost() {
		return this.articlePost;
	}

	/**
	 * ユーザID を設定します.
	 * 
	 * @param userId
	 *            ユーザID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * ユーザID を取得します.
	 * 
	 * @return ユーザID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((articleId == null) ? 0 : articleId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Article other = (Article) obj;
		if (articleId == null) {
			if (other.articleId != null) {
				return false;
			}
		} else if (!articleId.equals(other.articleId)) {
			return false;
		}
		return true;
	}

}
