package jp.co.create.dto;

import java.io.Serializable;

/**
 * ユーザ管理 モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ユーザID. */
	private Integer userId;

	/** ユーザ名. */
	private String userName;

	/** ユーザパスワード. */
	private String userPass;

	/**
	 * コンストラクタ.
	 */
	public User() {
	}

	/**
	 * ユーザID を設定します.
	 *
	 * @param userId
	 *            ユーザID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * ユーザID を取得します.
	 *
	 * @return ユーザID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * ユーザ名 を設定します.
	 *
	 * @param userName
	 *            ユーザ名
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * ユーザ名 を取得します.
	 *
	 * @return ユーザ名
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * ユーザパスワード を設定します.
	 *
	 * @param userPass
	 *            ユーザパスワード
	 */
	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	/**
	 * ユーザパスワード を取得します.
	 *
	 * @return ユーザパスワード
	 */
	public String getUserPass() {
		return this.userPass;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (userId == null) {
			if (other.userId != null) {
				return false;
			}
		} else if (!userId.equals(other.userId)) {
			return false;
		}
		return true;
	}

}
